#!/usr/bin/bash -x

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/../../../../lib/helpers.sh
source /etc/environment

etcd-set /logging/config/journald-pos-file "/tmp/fluentd_journald.pos"
etcd-set /logging/config/fluentd-forwarder-port "5170"
etcd-set /logging/config/fluentd-router-port "24224"
etcd-set /logging/config/fluentd-monitor-port "24220"
etcd-set /logging/config/fluentd-router-weight "60"
etcd-set /logging/config/fluentd-ethosplugin-cache-size "1000"
etcd-set /logging/config/fluentd-ethosplugin-cache-ttl "3600"
etcd-set /logging/config/fluentd-ethosplugin-get-tag-flag "false"
etcd-set /logging/config/fluentd-ethosplugin-container-tag "CONTAINER_ID"
etcd-set /logging/config/fluentd-ethosplugin-logtype-rule 'LOG_TYPE ^(\w+) logtype.$1'
etcd-set /logging/config/fluentd-forward-send-timeout "60s"
etcd-set /logging/config/fluentd-forward-recover-wait "10s"
etcd-set /logging/config/fluentd-forward-heartbeat-type "udp"
etcd-set /logging/config/fluentd-forward-heartbeat-interval "1s"
etcd-set /logging/config/fluentd-forward-phi-failure-detector "true"
etcd-set /logging/config/fluentd-forward-phi-threshold "16"
etcd-set /logging/config/fluentd-forward-hard-timeout "60s"
etcd-set /logging/config/fluentd-forward-buffer-type "memory"
etcd-set /logging/config/fluentd-forward-buffer-queue-limit "64"
etcd-set /logging/config/fluentd-forward-buffer-chunk-limit "8m"
etcd-set /logging/config/fluentd-forward-flush-interval "60s"
etcd-set /logging/config/fluentd-forward-flush-at-shutdown "true"
etcd-set /logging/config/fluentd-forward-retry-wait "1s"
etcd-set /logging/config/fluentd-forward-max-retry-wait "24h"
etcd-set /logging/config/fluentd-forward-retry-limit "17"
etcd-set /logging/config/fluentd-forward-disable-retry-limit "false"
etcd-set /logging/config/fluentd-forward-num-threads "1"
etcd-set /logging/config/fluentd-httpext-buffer-type "memory"
etcd-set /logging/config/fluentd-httpext-buffer-queue-limit "16m"
etcd-set /logging/config/fluentd-httpext-buffer-chunk-limit "8m"
etcd-set /logging/config/fluentd-httpext-flush-interval "60s"
etcd-set /logging/config/fluentd-httpext-flush-at-shutdown "true"
etcd-set /logging/config/fluentd-httpext-retry-wait "1s"
etcd-set /logging/config/fluentd-httpext-max-retry-wait "24h"
etcd-set /logging/config/fluentd-httpext-retry-limit "17"
etcd-set /logging/config/fluentd-httpext-disable-retry-limit "false"
etcd-set /logging/config/fluentd-httpext-endpoint-url "splunk-us-hec-external.adobelaas.com/services/collector"
etcd-set /logging/config/fluentd-httpext-http-method "post"
etcd-set /logging/config/fluentd-httpext-serializer "json"
etcd-set /logging/config/fluentd-httpext-use-ssl "true"
etcd-set /logging/config/fluentd-httpext-splunk-hec-token "Splunk BE07EE32-C89B-4008-B71C-9C72B65F2144"
